package command;

import action.Action;
import fileio.ActionInputData;

public abstract class Command extends Action {

    public Command(final ActionInputData actionInputData) {
        super(actionInputData);
    }
    /**
     * Executes the command specified by actionInputData
     * @return the output message generated by the command
     */
    public abstract String executeAction();
}
