package command;

import common.Constants;
import entertainment.Video;
import fileio.ActionInputData;
import user.User;

public final class Favorite extends Command {

    public Favorite(final ActionInputData actionInputData) {
        super(actionInputData);
    }

    /**
     * Adds video to user's favorite list
     * @return the output message generated by the favorite command
     */
    public String executeAction() {
        //  Get title of video added to favorite list
        String title = getActionInputData().getTitle();

        //  Get user by username
        User user = getUser(getActionInputData().getUsername());

        //  Video hasn't been watched before
        if (!isSeen(user, title)) {
            return Constants.ERROR + title + Constants.NOT_SEEN;
        }

        //  Video is already in favorite list
        if (user.getFavoriteMovies().contains(title)) {
            return Constants.ERROR + title + Constants.ALREADY_FAV;
        }

        //  Add video to favorite list
        user.getFavoriteMovies().add(title);

        //  Note that video was picked as a favorite by a user
        Video favVideo = getVideo(title);
        //  Update
        favVideo.setFavoriteChoice(favVideo.getFavoriteChoice() + 1);

        //  Video was added successfully to favorite list
        return Constants.SUCCESS + title + Constants.ADDED_FAV;
    }
}
