package action;

import common.Database;
import entertainment.Video;
import fileio.ActionInputData;
import user.User;

public abstract class Action {
    private final ActionInputData actionInputData;

    public Action(final ActionInputData actionInputData) {
        this.actionInputData = actionInputData;
    }

    public final ActionInputData getActionInputData() {
        return actionInputData;
    }

    /**
     * Gets user by username
     * @param username the searched username
     * @return user
     */
    public User getUser(final String username) {
        for (User user : Database.getDatabase().getUsers()) {
            if (user.getUsername().equals(username)) {
                return user;
            }
        }
        return null;
    }

    /**
     * Gets video by title
     * @param title the searched title
     * @return video
     */
    public Video getVideo(final String title) {
        for (Video video : Database.getDatabase().getAllVideos()) {
            if (video.getTitle().equals(title)) {
                return video;
            }
        }
        return null;
    }

    /**
     * Validates if video was watched by user
     * @param user the user
     * @param title the title of
     * @return true if video was viewed before by user, otherwise false
     */
    public boolean isSeen(final User user, final String title) {
        return user.getHistory().containsKey(title);
    }

    /**
     * Executes the action specified by actionInputData
     * @return the output message generated by the action
     */
    public abstract String executeAction();
}
